pipeline {
    agent any
    triggers {
        pollSCM('H/5 * * * *')
    }
    stages {
        stage('OpenShift Project') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                            echo "Project: ${openshift.project()}"
                        }
                    }
                }
            }
        }
    }
}
