// Manage Jenkins master service
@Library('Utils') _

pipeline {
    agent any

    triggers {
        pollSCM('H/15 * * * *')
    }

    stages {
        stage('S2I build Jenkins with custom configuration') {
            when {
                expression {
                    findFileChangesContains("jenkins")
                }

            }
            steps {
                openshiftBuild bldCfg: 'jenkins-custom'
            }
        }
    }
    post {
        failure {
            mail to: 'example@example.com',
            from: 'jenkins@example.com', replyTo: 'noreply@example.com',
            subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
            body: "Jenkins master build failed: ${env.BUILD_URL}"
        }
    }
}
