// Manage Jenkins master service
pipeline {
    agent any
    triggers {
        // OpenShift will also trigger the pipeline if the upstream 'jenkins' image changes
        pollSCM('H/5 * * * *')
    }
    stages {
        stage('S2I build Jenkins with custom configuration') {
            steps {
                openshiftBuild bldCfg: 'jenkins-custom'
            }
        }
    }
    post {
        failure {
            mail to: 'aweiteka@redhat.com',
            subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
            body: "Jenkins master build failed: ${env.BUILD_URL}"
        }
    }
}
