// Manage Jenkins master service
pipeline {
    agent any
    triggers {
        // OpenShift will also trigger the pipeline if the upstream 'jenkins' image changes
        pollSCM('H/5 * * * *')
    }
    stages {
        stage('Checkout') {
            steps {
                // ignore checkout part of excludedRegions
                checkout([$class: 'GitSCM',
                    branches: [[name: "refs/remotes/origin/master"]],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [[
                        $class: 'PathRestriction',
                        excludedRegions: '^ansible/.*\n^app/.*']],
                    submoduleCfg: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/RHsyseng/jenkins-on-openshift']]])
            }
        }
        stage('Trigger build') {
            steps {
                openshiftBuild bldCfg: 'jenkins-custom'
            }
        }
        stage('Verify build') {
            steps {
                openshiftBuild bldCfg: 'jenkins-custom', waitTime: '240', waitUnit: 'sec'
            }
        }
        stage('Verify deployment') {
            steps {
                openshiftVerifyDeployment depCfg: 'jenkins', waitTime: '360', waitUnit: 'sec'
            }
        }
    }
}
