apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: app-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "app-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
          env:
            - name: SOURCE_REPOSITORY_URL
              value: "${SOURCE_REPOSITORY_URL}"
            - name: SOURCE_REPOSITORY_REF
              value: "${SOURCE_REPOSITORY_REF}"
            - name: APP_DC_NAME
              value: "${APP_DC_NAME}"
            - name: IMAGE_STREAM_NAME
              value: "${IMAGE_STREAM_NAME}"
            - name: IMAGE_STREAM_LATEST_TAG
              value: "${IMAGE_STREAM_LATEST_TAG}"
            - name: APP_TEMPLATE_PATH
              value: "${APP_TEMPLATE_PATH}"
            - name: DEV_PROJECT
              value: "${DEV_PROJECT}"
            - name: STAGE_PROJECT
              value: "${STAGE_PROJECT}"
            - name: REGISTRY_PROJECT
              value: "${REGISTRY_PROJECT}"
            - name: REGISTRY_URI
              value: "${REGISTRY_URI}"
            - name: DEV_URI
              value: "${DEV_URI}"
            - name: STAGE_URI
              value: "${STAGE_URI}"
            - name: STAGE_SECRET_NAME
              value: "${STAGE_SECRET_NAME}"
    triggers: {}
parameters:
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/tchughesiv/jenkins-on-openshift.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Imagestream name
  name: IMAGE_STREAM_NAME
  required: true
  value: nodejs-mongo-persistent
- description: Imagestream tag
  name: IMAGE_STREAM_LATEST_TAG
  required: true
  value: latest
- description: Application deploymentconfig name
  name: APP_DC_NAME
  required: true
  value: nodejs-mongo-persistent
- description: Application template path
  name: APP_TEMPLATE_PATH
  required: true
  value: "app/openshift/nodejs-mongodb-persistent.json"
- description: "Registry hostname that images are pushed to"
  name: REGISTRY_URI
  required: true
  value: "registry.example.com:5000"
- description: Dev project
  name: DEV_PROJECT
  required: true
  value: lifecycle
- description: Stage project
  name: STAGE_PROJECT
  required: true
  value: lifecycle
- description: Registry project
  name: REGISTRY_PROJECT
  required: true
  value: lifecycle
- description: Dev cluster hostname
  name: DEV_URI
  required: true
  value: "insecure://dev.example.com:8443"
- description: Stage cluster hostname
  name: STAGE_URI
  required: true
  value: "insecure://stage.example.com:8443"
- description: Stage secret name
  name: STAGE_SECRET_NAME
  required: true
  value: "stage-api"
